// Copyright 2017-2023 @azero.dev/apps authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@azero.dev/apps', path: 'auto', type: 'auto', version: '0.127.2-2-x' };
